name: Scrape Spreadsheet

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 3 * *' # Runs everyday at 3:00am UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Set up Tokens
        run: |
          echo '{"access_token":"${{ secrets.ACCESS_TOKEN }}","token_type":"${{ secrets.TOKEN_TYPE }}","refresh_token":"${{ secrets.REFRESH_TOKEN }}","expiry":"${{ secrets.EXPIRY }}"}' > token.json
      
      - name: Build
        run: go build
      
      - name: Scrape spreadsheet
        run: ./scrape

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated metaData.json via workflow"
  